### ISSUE TITLE
Fix BelongsToMany relation detections

### ISSUE THREAD

**Issue by Naoray** [Naoray/eloquent-model-analyzer#20]
Related: https://github.com/laravel-shift/factory-generator/issues/13

- [x] add test for BelongsToMany relations
- [x] modify [`RelationMethod@foreignKey()` method](
https://github.com/Naoray/eloquent-model-analyzer/blob/master/src/RelationMethod.php#L99-L106) to support BelongsToMany Relations
- [ ] add tests for other relation types

**Comment by tshafer** [comment]
I added the following to line 104 and got it working.

```
    if ($relationObj instanceof BelongsToMany) {
         return $relationObj->getForeignPivotKeyName();
    }
```
